version: "3.4"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

  api:
    build: .
    container_name: api-delivery
    environment:
      - .env
    ports:
      - "8080:8080"
    links:
      - postgres


